"""add_llm_and_voice_config_to_prompt_template

Revision ID: 143f4d69082d
Revises: 
Create Date: 2026-02-13 15:34:30.575446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '143f4d69082d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_calls_prompt'), 'calls', type_='foreignkey')
    op.drop_table('agents')
    op.drop_table('models')
    op.drop_index(op.f('idx_prompts_capabilities'), table_name='prompts', postgresql_using='gin')
    op.drop_index(op.f('idx_prompts_model_id'), table_name='prompts')
    op.drop_index(op.f('idx_prompts_name'), table_name='prompts')
    op.drop_table('prompts')
    op.alter_column('appointments', 'is_handled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_foreign_key(None, 'appointments', 'calls', ['call_id'], ['id'])
    op.alter_column('calls', 'direction',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('calls', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_calls_counterpart'), table_name='calls')
    op.drop_index(op.f('idx_calls_prompt_id'), table_name='calls')
    op.drop_index(op.f('idx_calls_started_at'), table_name='calls')
    op.drop_index(op.f('idx_calls_status'), table_name='calls')
    op.create_index(op.f('ix_calls_counterpart'), 'calls', ['counterpart'], unique=False)
    op.create_index(op.f('ix_calls_handler_type'), 'calls', ['handler_type'], unique=False)
    op.create_index(op.f('ix_calls_prompt_id'), 'calls', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_calls_sip_call_id'), 'calls', ['sip_call_id'], unique=False)
    op.create_index(op.f('ix_calls_started_at'), 'calls', ['started_at'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.drop_table_comment(
        'calls',
        existing_comment='通话记录表',
        schema=None
    )
    op.add_column('prompt_templates', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('prompt_templates', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('prompt_templates', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('prompt_templates', sa.Column('max_tokens', sa.Integer(), nullable=True))
    op.add_column('prompt_templates', sa.Column('voice_provider', sa.String(length=50), nullable=True))
    op.add_column('prompt_templates', sa.Column('voice_id', sa.String(length=100), nullable=True))
    op.add_column('prompt_templates', sa.Column('voice_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_prompt_templates_active'), table_name='prompt_templates')
    op.drop_index(op.f('idx_prompt_templates_category'), table_name='prompt_templates')
    op.drop_index(op.f('idx_prompt_templates_code'), table_name='prompt_templates')
    op.drop_constraint(op.f('prompt_templates_code_key'), 'prompt_templates', type_='unique')
    op.create_index(op.f('ix_prompt_templates_category'), 'prompt_templates', ['category'], unique=False)
    op.create_index(op.f('ix_prompt_templates_code'), 'prompt_templates', ['code'], unique=True)
    op.create_index(op.f('ix_prompt_templates_is_active'), 'prompt_templates', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_templates_is_active'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_code'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_category'), table_name='prompt_templates')
    op.create_unique_constraint(op.f('prompt_templates_code_key'), 'prompt_templates', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_prompt_templates_code'), 'prompt_templates', ['code'], unique=False)
    op.create_index(op.f('idx_prompt_templates_category'), 'prompt_templates', ['category'], unique=False)
    op.create_index(op.f('idx_prompt_templates_active'), 'prompt_templates', ['is_active'], unique=False)
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('prompt_templates', 'voice_settings')
    op.drop_column('prompt_templates', 'voice_id')
    op.drop_column('prompt_templates', 'voice_provider')
    op.drop_column('prompt_templates', 'max_tokens')
    op.drop_column('prompt_templates', 'temperature')
    op.drop_column('prompt_templates', 'llm_model')
    op.drop_column('prompt_templates', 'llm_provider')
    op.create_table_comment(
        'calls',
        '通话记录表',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_calls_prompt'), 'calls', 'prompts', ['prompt_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_started_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_sip_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_prompt_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_handler_type'), table_name='calls')
    op.drop_index(op.f('ix_calls_counterpart'), table_name='calls')
    op.create_index(op.f('idx_calls_status'), 'calls', ['status'], unique=False)
    op.create_index(op.f('idx_calls_started_at'), 'calls', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('idx_calls_prompt_id'), 'calls', ['prompt_id'], unique=False)
    op.create_index(op.f('idx_calls_counterpart'), 'calls', ['counterpart'], unique=False)
    op.alter_column('calls', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('calls', 'direction',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'is_handled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('welcome_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('closing_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"tts_enabled": false, "appointment_logging": false}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('voice_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=20), server_default=sa.text("'1.0'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('prompts_pkey')),
    comment='Prompt模板表'
    )
    op.create_index(op.f('idx_prompts_name'), 'prompts', ['name'], unique=False)
    op.create_index(op.f('idx_prompts_model_id'), 'prompts', ['model_id'], unique=False)
    op.create_index(op.f('idx_prompts_capabilities'), 'prompts', ['capabilities'], unique=False, postgresql_using='gin')
    op.create_table('models',
    sa.Column('id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('models_pkey')),
    comment='支持的LLM模型表'
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('llm_provider', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('voice', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("llm_provider::text = ANY (ARRAY['openai'::character varying, 'anthropic'::character varying, 'azure'::character varying, 'google'::character varying]::text[])", name=op.f('agents_llm_provider_check')),
    sa.CheckConstraint('temperature >= 0::numeric AND temperature <= 2::numeric', name=op.f('agents_temperature_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('agents_pkey')),
    sa.UniqueConstraint('name', name=op.f('agents_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Agent配置表'
    )
    # ### end Alembic commands ###
