"""add dynamic schema fields to appointment

Revision ID: 366cf503647a
Revises: c9772e165a8f
Create Date: 2026-03-04 12:15:43.599970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '366cf503647a'
down_revision: Union[str, Sequence[str], None] = 'c9772e165a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('prompt_id', sa.UUID(), nullable=True))
    op.add_column('appointments', sa.Column('type_name', sa.String(length=50), nullable=True))
    op.add_column('appointments', sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_appointments_prompt_id'), 'appointments', ['prompt_id'], unique=False)
    op.create_index(op.f('ix_appointments_type_name'), 'appointments', ['type_name'], unique=False)
    op.create_foreign_key(None, 'appointments', 'prompt_templates', ['prompt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_type_name'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_prompt_id'), table_name='appointments')
    op.drop_column('appointments', 'extracted_data')
    op.drop_column('appointments', 'type_name')
    op.drop_column('appointments', 'prompt_id')
    # ### end Alembic commands ###
